server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVICE_URI:http://eureka-service:8761/eureka}
    instance:
      hostname: localhost
      
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microserviciosdb
    username: postgres
    password: '12345'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update